# Example of needed secret keys
# Do NOT commit actual keys in this file, but keep them in secrets.yml instead

development:
  secret_key_base: 93024dd8ecf1c1f5f561c6aeae31cb60451256196cd74bc6ce8d08f4cbee82063ace66ec02f3d8ebe79eae4f40dbf953dd52bcd559aa1a4bf0df589f4415fa9b

test:
  secret_key_base: 441e45bb73b46dc3efa78273657b396f61b0238aae2e05edb2c3b5f6376b4843cb9ead03134e0c701884cdff21ded7058e81c53ddabe47acce2fdb15c623b821

# Capistrano settings
# Ideally we could change this in a per environment setting, but meh.
# Only have prod for the server rn anyway.
capistrano:
  paths:
    back:  PATH_TO_BACK
    front: PATH_TO_FRONT
  ssh_options:
    user: USER_TO_SSH_WITH
    any_other_options: BADGERS!
